## This file has been generated by regen.py
## Changes may be overwritten the next time 
## configs are re-generated

# Colors
# black
foreground='%(base05)s'
background='%(base00)s'

base00='%(base01)s'
base08='%(base04)s'

# red
base01='%(base11)s'
base09='%(base11)s'

# green
base02='%(base14)s'
base10='%(base12)s'

# yellow
base03='%(base13)s'
base11='%(base13)s'

# blue
base04='%(base09)s'
base12='%(base09)s'

# magenta
base05='%(base15)s'
base13='%(base10)s'

# cyan
base06='%(base08)s'
base14='%(base07)s'

# white
base07='%(base05)s'
base15='%(base06)s'

# vim:ft=sh
